import Button from '@/components/atoms/Button'
import Typography from '@/components/atoms/Typography'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      Index File
      <Typography as="body1">Oi</Typography>
      <Button>Teste</Button>
    </div>
  )
}

export default Home
